### ISSUE TITLE
[BUG]: tracking issue for PyPy 7.3.6 support (PyPy 3.8)

### ISSUE THREAD

**Issue by henryiii** [pybind/pybind11#3408]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### Problem description

We are having issues with the PyPy update, so I'm going to avoid making it and just list the problems here, eventually opening up another PR (currently mixed into #3368). This will also focus only on supporting it, not on building binaries with it, which is a bad idea (on PyPy3.7, anyway) - users should wait till 7.3.7 to build binaries (and existing ones like possibly NumPy won't work).

#### For both 3.7 and 3.8:
* [ ] `test_to_python` returns 1 from `cstats.alive()`

#### For 3.8 Unix:

* [ ] `test_int_convert` does not produce a warning (was not included before)
* [ ] `test_numpy_int_convert` does not produce a warning (Also was not included before)
* [ ] `PyLong_AsLong` implementation does not contain the updates made in CPython to call `__index__`.
* [ ] `test_eval_empty_globals` does not contain `__builtins__` (or anything).
* [ ] `test_python_alreadyset_in_destructor` returns False from `triggered[0]`

#### For 3.8 Windows:

* [ ] Dies with `ImportError: initialization failed`. Probably from the issue we've always had on 3.8 not being able to run the cross module tests on Windows.

#### For 2.7 macOS:

It seems the parallel setuptools_helpers test hangs. Could be intermittent, a CI issue, or something else, but could be related to PyPy 7.3.6. Edit: rerunning made it pass.

**Comment by mattip** [comment]
[Here is](https://github.com/conda-forge/pytomlpp-feedstock/pull/1#issuecomment-972738986) a new failure. I think it can be described as: calling `std::cout << value.cast<py::list>() << std::endl` succeeds in CPython and fails to compile in PyPy. This case is hit when `value` is 
```
class a:
        pass

value = [a()]
```

**Comment by mattip** [comment]
> The `test_int_convert` test is broken, `IntAndIndex()` returns the value for `__int__()` instead of `__index__()` from `PyLong_AsLong`.

This is fixed on latest pypy3.8 nightlies.

**Comment by henryiii** [comment]
> `std::cout << py::cast<py::list>(value) << std::endl`

I tried a little test and this seemed to be fine.

```diff
diff --git a/noxfile.py b/noxfile.py
index 4adffac2..3eedd455 100644
--- a/noxfile.py
+++ b/noxfile.py
@@ -2,7 +2,7 @@ import nox

 nox.options.sessions = ["lint", "tests", "tests_packaging"]

-PYTHON_VERISONS = ["2.7", "3.5", "3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]
+PYTHON_VERISONS = ["2.7", "3.5", "3.6", "3.7", "3.8", "3.9", "3.10", "3.11", "pypy3.7"]


 @nox.session(reuse_venv=True)
diff --git a/tests/test_stl.cpp b/tests/test_stl.cpp
index bc5c6553..ce2953fd 100644
--- a/tests/test_stl.cpp
+++ b/tests/test_stl.cpp
@@ -522,4 +522,7 @@ TEST_SUBMODULE(stl, m) {
         []() { return new std::vector<bool>(4513); },
         // Without explicitly specifying `take_ownership`, this function leaks.
         py::return_value_policy::take_ownership);
+
+    // Test list printing
+    m.def("print_as_list", [](const py::object &any){std::cout << py::cast<py::list>(any);});
 }
diff --git a/tests/test_stl.py b/tests/test_stl.py
index e2179759..d939ce4f 100644
--- a/tests/test_stl.py
+++ b/tests/test_stl.py
@@ -356,3 +356,14 @@ def test_return_vector_bool_raw_ptr():
     v = m.return_vector_bool_raw_ptr()
     assert isinstance(v, list)
     assert len(v) == 4513
+
+
+def test_print_list(capsys):
+    m.print_as_list([])
+
+    class A:
+        pass
+
+    m.print_as_list([A()])
+
+    assert False
```

This spits out `[][<test_stl.test_print_list.<locals>.A object at 0x00007fa2a8324020>]`.

**Comment by mattip** [comment]
Maybe there is some subtle difference between `value.cast<py::list>()` and `py::cast<py::list>(value)`?

**Comment by henryiii** [comment]
There shouldn't be, but just I tried that anyway, same results. Does the same thing happen if you do `throw py::type_error(py::str("not a valid type for conversion {}").format(it));`?

**Comment by henryiii** [comment]
Unrelated: @mattip could PyPy binaries for macOS please be built with 10.9+ instead of 10.7+ compatibility like the CPython binaries? Setting 10.7 means that these are broken out-of-the box when trying to build, since 10.9 was the first macOS version to use libc++, and libstdc++ was removed a few years ago, meaning targeting anything less than 10.9 is broken on modern macOS's. And the extension default is to match what the Python binaries target, and they target 10.7.

**Comment by henryiii** [comment]
(Wheel building tools like cibulidwheel set the MACOS_DEPLOYMENT_TARGET, so it only affects local builds. I can't build pytomlpp locally though without manually forcing `MACOS_DEPLOYMENT_TARGET`.)

**Comment by mattip** [comment]
> please be built with 10.9+ instead of 10.7+ compatibility like the CPython binaries

Do you know which PR bumped it?

**Comment by henryiii** [comment]
It used to be 10.6 when they provided FAT binaries, before they went to 64 bit only, that's when they became 10.9+ only. It's never been 10.7, IIRC pypy needed 10.7 instead of 10.6 for some reason. But you really, really want to be 10.9, due to the change to libc++. I can't get `pytomlpp` to build locally because it insists on 10.7 and then can't find libstdc++.

See https://www.python.org/downloads/release/python-365/ -> macOS users, and this was also done to 2.7 (but not 3.5). Python 3.8.0 was the first to remove the old 32/64 binary format.

**Comment by henryiii** [comment]
Also, it seems like PyPy is burning in 10.7 regardless of the OS it was built on when nothing is set. While Python defaults to the current OS version, and only the distributed binaries have older versions set. This means homebrew python, conda-forge python, etc. all have a much higher OS version than the official binaries, which is why we only use the official binaries for building wheels in cibuildwheel. But it also means that users trying to build code locally aren't having to worry about old compatibility issues like limited C++17 support (unless they download the official binaries, which many macOS users do not do).

**Comment by mattip** [comment]
Does PyPy from conda-forge/homebrew also pin to 10.7?

**Comment by mattip** [comment]
> Also, it seems like PyPy is burning in 10.7 regardless of the OS it was built on when nothing is set

Sorry, I am not really fluent in macOS. What is wrong and what would the fix look like? I didn't understand the rest of the comment.

**Comment by mattip** [comment]
`d={}; eval("1", d); assert "__builtins__" in d` now works on PyPy nightly.

**Comment by mattip** [comment]
@henryiii PyPy has somewhat redone its macOS builds to accomodate arm64 builds. Do [the nightlies](https://buildbot.pypy.org/nightly/) (py3.8, py3.9) work any better now?
