### ISSUE TITLE
[META]: Clarify license metadata

### ISSUE THREAD

**Issue by LecrisUT** [pybind/pybind11#5093]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### What version (or hash if on master) of pybind11 are you using?

N/A

### Problem description

It is unclear what version of BSD this project is licensed under. It would be nice to update the metadata to clarify this, specifically in a SPDX compatible format

### Is this a regression? Put the last known working version here if it is.

Not a regression
